### ISSUE TITLE
Implement per host overrides

### ISSUE THREAD

**Issue by viglesiasce** [viglesiasce/euca-deploy#30]
In the environment file, each machine should be allowed its own override parameters. I propose a second section that is override_attributes. This can contain the following types of overrides:
- Per role
- Per host
- Per cluster

For example:

```
## these apply to all machines
default_attributes:
  eucalyptus:
    cloud-opts: -Xmx4g
override_attributes:
  # These apply only to 1 machine
  role:
    cloud-controller:
      eucalyptus:
        cloud-opts: -Xmx48g --bind-addr 10.111.10.5
    node-controller:
      eucalyptus:
        nc:
          max-cores: 32
  host:
    10.1.1.55:
       eucalyptus:
        nc:
          max-cores: 64
  cluster:
     my-cluster-name:
         eucalyptus:
            cloud-opts: -Xmx16g
```
